import { createRequire } from 'module';
const require = createRequire(import.meta.url);
const { chromium, devices } = require(process.env.NPMG + '/playwright');
const browser = await chromium.launch({ args: ['--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader'] });
const page = await (await browser.newContext({ viewport: { width: 900, height: 650 } })).newPage();
const errs = []; page.on('pageerror', e => errs.push(e.message));
await page.goto('http://localhost:8765/');
await page.waitForFunction(() => window.__game, null, { timeout: 90000 });
await page.evaluate(() => { const g = __game; g.applyQuality('mid'); g.dropAt(0); g.buy('refill'); g.spawnDoll('jelly.9', 1, { x: 0, y: 1, z: 2.5 }); g.simulate(1.5); g.checkAchievements(); });
const pts = await page.evaluate(() => __game.achPoints);
await page.click('#achBtn'); await page.waitForTimeout(200);
await page.click('button[data-achtab="shop"]'); await page.waitForTimeout(200);
await page.click('button[data-decorbuy="tableRed"]'); await page.waitForTimeout(100);
await page.evaluate(() => { const b = document.querySelector('button[data-cheat="ach"]'); for (let i = 0; i < 20; i++) b.click(); });
await page.click('button[data-achtab="list"]'); await page.click('button[data-achtab="shop"]');
await page.click('button[data-decorbuy="coinRose"]'); await page.click('button[data-decorbuy="bgPlum"]'); await page.waitForTimeout(200);
await page.screenshot({ path: '/tmp/pd-shots/ach-shop2.png' });
await page.click('#achClose'); await page.waitForTimeout(800);
await page.screenshot({ path: '/tmp/pd-shots/decor.png' });
await page.evaluate(() => __game.saveGame());
await page.reload(); await page.waitForFunction(() => window.__game, null, { timeout: 90000 });
const eq = await page.evaluate(() => JSON.parse(localStorage.getItem('pretty_drop_save')).equipped);
console.log(JSON.stringify({ pts, eq, errs }));
await browser.close();
