import { createRequire } from 'module';
const require = createRequire(import.meta.url);
const { chromium, devices } = require(process.env.NPMG + '/playwright');
const browser = await chromium.launch({ args: ['--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader'] });
const page = await (await browser.newContext({ viewport: { width: 900, height: 650 } })).newPage();
const errs = []; page.on('pageerror', e => errs.push(e.message)); page.on('console', m => { if (m.type()==='error') errs.push(m.text()); });
await page.goto('http://localhost:8765/');
await page.waitForFunction(() => window.__game, null, { timeout: 90000 });
await page.evaluate(() => { const g = __game; g.applyQuality('mid'); g.dropProp('ticket'); g.dropProp('item'); g.dropProp('item'); g.simulate(3); });
await page.waitForTimeout(800);
await page.screenshot({ path: '/tmp/pd-shots/props.png' });
const r = await page.evaluate(() => {
  const g = __game; const out = {};
  out.onTable = g.props.map(p => p.kind);
  g.spawnProp('ticket', 'ticket', { x: 0, y: 1, z: 3.6 });
  g.spawnProp('item', 'wind', { x: 1, y: 1, z: 3.6 });
  g.simulate(1.5);
  out.free = g.freeSpins;
  out.wheelOpen = document.getElementById('wheel').classList.contains('show');
  out.itemsUsed = g.stats.itemsUsed;
  return out;
});
await page.click('#freeSpinBtn'); await page.waitForTimeout(4200);
const res1 = await page.textContent('#wheelResult');
const w0 = await page.evaluate(() => __game.wallet);
await page.click('#paySpinBtn'); await page.waitForTimeout(4200);
const res2 = await page.textContent('#wheelResult');
await page.screenshot({ path: '/tmp/pd-shots/wheel2.png' });
console.log(JSON.stringify({ r, res1, res2, w0, w1: await page.evaluate(() => __game.wallet), errs }));
await browser.close();
