import { createRequire } from 'module';
const require = createRequire(import.meta.url);
const { chromium, devices } = require(process.env.NPMG + '/playwright');
const browser = await chromium.launch({ args: ['--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader'] });
const page = await (await browser.newContext(devices['iPhone 13'])).newPage();
const errs = []; page.on('pageerror', e => errs.push(e.message));
await page.goto('http://localhost:8765/');
await page.waitForFunction(() => window.__game, null, { timeout: 90000 });
await page.evaluate(() => { __game.applyQuality('low'); });
await page.waitForTimeout(300);
const ready0 = await page.evaluate(() => document.getElementById('shopBtn').classList.contains('ready'));
await page.tap('#shopBtn'); await page.waitForTimeout(200);
const items0 = await page.$$eval('#shopList .item .name', els => els.map(e => e.textContent));
await page.tap('button[data-buy="refill"]'); await page.waitForTimeout(200);
const items1 = await page.$$eval('#shopList .item .name', els => els.map(e => e.textContent));
await page.evaluate(() => __game.setWallet(60)); await page.waitForTimeout(300);
await page.tap('button[data-buy="speed"]'); await page.waitForTimeout(300);
await page.screenshot({ path: '/tmp/pd-shots/shop.png' });
const items2 = await page.$$eval('#shopList .item .name', els => els.map(e => e.textContent));
await page.tap('#shopClose');
const prices = await page.evaluate(() => Object.fromEntries(Object.entries(__game.UPGRADES).map(([k,u]) => [k, u.prices])));
const n0 = await page.evaluate(() => __game.coins.length);
await page.evaluate(() => __game.startRain());
await page.waitForTimeout(400);
await page.screenshot({ path: '/tmp/pd-shots/rain.png' });
await page.waitForTimeout(5000);
const n1 = await page.evaluate(() => ({ n: __game.coins.length, rain: __game.rain }));
console.log(JSON.stringify({ ready0, items0, items1, items2, prices, n0, n1, errs }));
await browser.close();
