import { createRequire } from 'module';
const require = createRequire(import.meta.url);
const { chromium, devices } = require(process.env.NPMG + '/playwright');
const browser = await chromium.launch({ args: ['--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader'] });
const page = await (await browser.newContext(devices['iPhone 13'])).newPage();
const errs = []; page.on('pageerror', e => errs.push(e.message)); page.on('console', m => { if (m.type()==='error') errs.push(m.text()); });
await page.goto((process.env.BASE || 'http://localhost:8765/'));
await page.waitForFunction(() => window.__game, null, { timeout: 90000 });
await page.tap('#settingsBtn'); await page.tap('#settings .tab[data-tab="other"]');
await page.screenshot({ path: '/tmp/pd-shots/cheat.png' });
await page.tap('button[data-cheat="coin1000"]'); await page.tap('button[data-cheat="legend"]'); await page.tap('button[data-cheat="sets"]');
const w = await page.evaluate(() => __game.wallet);
await page.tap('#settingsBtn');
await page.evaluate(() => { __game.spawnDoll('jelly.9', 1, { x: 0, y: 1, z: 2.5 }); __game.simulate(1.5); });
await page.tap('#bookBtn'); await page.waitForTimeout(200);
await page.tap('.bookCell.owned'); await page.waitForTimeout(1500);
await page.screenshot({ path: '/tmp/pd-shots/viewer.png' });
const prices = await page.evaluate(() => Object.fromEntries(__game.UPGRADE_KEYS.map(k => [k, __game.UPGRADES[k].prices.join(',')])));
console.log(JSON.stringify({ w, prices, errs }));
await browser.close();
