import { createRequire } from 'module';
const require = createRequire(import.meta.url);
const { chromium, devices } = require(process.env.NPMG + '/playwright');
const browser = await chromium.launch({ args: ['--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader'] });
const page = await (await browser.newContext(devices['iPhone 13'])).newPage();
const errs = []; page.on('pageerror', e => errs.push(e.message));
await page.goto((process.env.BASE || 'http://localhost:8765/'));
await page.waitForFunction(() => window.__game, null, { timeout: 90000 });
await page.evaluate(() => __game.applyQuality('low'));
await page.tap('#settingsBtn'); await page.tap('#settings .tab[data-tab="sound"]');
await page.$eval('#volSlider', el => { el.value = 3; el.dispatchEvent(new Event('input', { bubbles: true })); el.dispatchEvent(new Event('change', { bubbles: true })); });
await page.screenshot({ path: '/tmp/pd-shots/vol.png' });
await page.reload(); await page.waitForFunction(() => window.__game, null, { timeout: 90000 });
console.log(JSON.stringify({ v: await page.evaluate(() => __game.soundOn.volume), errs }));
await browser.close();
