import { createRequire } from 'module';
const require = createRequire(import.meta.url);
const { chromium, devices } = require(process.env.NPMG + '/playwright');
const browser = await chromium.launch({ args: ['--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader'] });
const page = await (await browser.newContext(devices['iPhone 13'])).newPage();
const errs = []; page.on('pageerror', e => errs.push(e.message)); page.on('console', m => { if (m.type()==='error') errs.push(m.text()); });
await page.goto('http://localhost:8765/');
await page.waitForFunction(() => window.__game, null, { timeout: 90000 });
await page.evaluate(() => __game.applyQuality('low'));
const r0 = await page.evaluate(() => {
  const g = __game;
  g.spawnDoll('jelly.9', 1, { x: 0, y: 1, z: 2.5 }); g.simulate(1.5);
  const t = g.tickets;
  for (const k of Object.keys(g.items)) g.items[k] += 2;
  const won0 = g.won;
  g.useItem('wind'); g.simulate(2.5);
  const windWon = g.won - won0;
  g.useItem('glue');
  const glued = g.coins.filter(c => c.glued).length;
  g.simulate(1);
  g.useItem('quake'); g.simulate(2);
  return { t, windWon, glued, n: g.coins.length };
});
await page.waitForTimeout(300);
await page.screenshot({ path: '/tmp/pd-shots/items.png' });
await page.tap('#itemBar button[data-open="wheel"]'); await page.waitForTimeout(200);
await page.tap('#spinBtn'); await page.waitForTimeout(4500);
await page.screenshot({ path: '/tmp/pd-shots/wheel.png' });
const res = await page.textContent('#wheelResult');
console.log(JSON.stringify({ r0, res, tickets: await page.evaluate(() => __game.tickets), errs }));
await browser.close();
